config/routes.rb
Funbet::Application.routes.draw do
  root to: 'dashboards#index'

  resources :authentications
  resources :sessions
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

	get '/auth/:provider/callback', to: 'sessions#create'

  resources :users
  get 'register' => 'users#new', as: :register

  resources :bets do
    post 'agree' => 'bets#agree', as: :agree
    post 'disagree' => 'bets#disagree', as: :disagree
    post 'complete' => 'bets#complete', as: :complete
    get 'verify' => 'bets#verify', as: :verify
    put 'verify' => 'bets#upload_verification', as: :upload_verification
  end

end

app/models/bet.rb
class Bet < ParseResource::Base
	fields :id, :loser_task, :outcome, :is_public, :proposition, :owner_id, :event_start

	attr_accessor :agreeing_choices, :disagreeing_choices, :verified_choices, :users, :user_choices, :owner

	def convert_bools!
		if self.outcome == '0'
			self.outcome = false
		elsif self.outcome == '1'
			self.outcome = true
		end

		if self.is_public == '0'
			self.is_public = false
		else
			self.is_public = true
		end
	end

	def id
		self.objectId
	end

	# Allow betting when (event_start not reached or not defined) and (outcome has not been decided yet)
	def betting_allowed
		((not self.event_start.present?) or Time.now < self.event_start) and (not self.outcome.present?)
	end

	# Betting is finished when (event_start reached or not defined)
	def betting_finished
		((not self.event_start.present?) or Time.now > self.event_start)
	end

	def user_choice_for(user)
		UserChoice.where(bet_id: self.id, user_id: user.id).first
	end

	def agreeing_choices
		@user_choices ||= user_choices.where(choice: true)
	end

	def disagreeing_choices
		@disagreeing_choices ||= user_choices.where(choice: false)
	end

	def verified_choices
		@verified_choices ||= user_choices.where(choice: !self.outcome, has_delivered: true)
	end

	def users
		@users ||= user_choices.map { |uc| uc.user }
	end

	def user_choices
		@user_choices ||= UserChoice.where(bet_id: self.id)
	end

	def owner
		@owner ||= User.find(self.owner_id)
	end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
	respond_to :html

	before_filter :authenticate_user!

  def index
    # @bets = Bet.all
		# respond_with(@bets)
    redirect_to root_path
  end

  def show
    @bet = Bet.find(params[:id])
		respond_with(@bet)
  end

  def new
    @bet = Bet.new
		respond_with(@bet)
  end

  def create
    # First create ans ave the bet
    # params[:owner_id] = current_user.id
    @bet = Bet.new
    @bet.proposition = params[:bet][:proposition]
    @bet.loser_task = params[:bet][:loser_task]
    @bet.is_public = params[:bet][:is_public]
    @bet.owner_id = current_user.id
		@bet.convert_bools!

		if @bet.save
			u = UserChoice.new(user_id: current_user.id, bet_id: @bet.id, choice: true)
			u.save

			# Send a simple sms notificatin to initialize the feedback loop
			sms = Sms.new
			sms.to_user = current_user
			sms.content = 'What a fun bet! We will let you know who the fool is to challenge your amazing foresight.'
			sms.deliver

			# Send a simple email
			msg = UserMailer.bet_created_message(@bet)
			msg.deliver!

			redirect_to root_path
		else
			redirect_to new_bet_path
		end
  end

  def destroy
    bet = Bet.find(params[:id])
    bet.destroy
		redirect_to bets_path
  end

  def complete
    choice = if params[:choice] == 'true' then true else false end
    bet = Bet.find(params[:bet_id])
    
    bet.outcome = choice
    bet.convert_bools!
    bet.save

    bet.user_choices.each do |user_choice|
      if user_choice.choice != bet.outcome
        user_choice.has_delivered = false

        # Send a simple sms notificatin to initialize the feedback loop
        sms = Sms.new
        sms.to_user = user_choice.user
        sms.content = "Uh oh! Looks like you lost the #{bet.proposition} bet. Go to betly.io to see your task."
        sms.deliver

        # Send a simple email
        msg = UserMailer.incorrect_choice_message(user_choice)
        msg.deliver!
      else
        # Send a simple sms notificatin to initialize the feedback loop
        sms = Sms.new
        sms.to_user = user_choice.user
        sms.content = "Congragulations! Your bet on #{bet.proposition} was correct. Wait for task verifications to show up on betly.io."
        sms.deliver

        # Send a simple email
        msg = UserMailer.correct_choice_message(user_choice)
        msg.deliver!
      end
    end

    redirect_to bet
  end

  def agree
    @bet = Bet.find(params[:bet_id])
    u = UserChoice.new(user_id: current_user.id, bet_id: @bet.id, choice: true)
    u.save

    # Send a simple sms notificatin to initialize the feedback loop
    sms = Sms.new
    sms.to_user = @bet.owner
    sms.content = 'Someone agreed with your bet on betly.io!'
    sms.deliver

    # Send a simple email
    msg = UserMailer.new_gambler_message(u)
    msg.deliver!

    redirect_to @bet
  end

  def disagree
    @bet = Bet.find(params[:bet_id])
    u = UserChoice.new(user_id: current_user.id, bet_id: @bet.id, choice: false)
    u.save

    # Send a simple sms notificatin to initialize the feedback loop
    sms = Sms.new
    sms.to_user = @bet.owner
    sms.content = 'Someone challenged you on betly.io!'
    sms.deliver

    # Send a simple email
    msg = UserMailer.new_gambler_message(u)
    msg.deliver!

    redirect_to @bet
  end

  def verify
    @bet = Bet.find(params[:bet_id])
    respond_with(@bet)
  end

  def upload_verification
    @bet = Bet.find(params[:bet_id])
    @user_choice = UserChoice.where(bet_id: @bet.id, user_id: current_user.id).first
    file = params[:bet][:verification_file]
    result = Bet.upload(file.tempfile, file.original_filename, content_type: file.content_type)
    @user_choice.verification_file = {"name" => result["name"], "__type" => "File"}
    @user_choice.has_delivered = true
    s = @user_choice.save

    # Let everyone know
    @bet.user_choices.each do |user_choice|
      # Send a simple sms notificatin to initialize the feedback loop
      sms = Sms.new
      sms.to_user = user_choice.user
      sms.content = "Hilarious! #{current_user.username} has uploaded a photo executing his loser task. Check it out."
      sms.deliver

      # Send a simple email
      msg = UserMailer.verification_added_message(user_choice, current_user)
      msg.deliver!
    end

    redirect_to @bet
  end

end

app/views/bets/_bet_details.html.haml
.bet-details.row.margin-top
  - if current_user.id == bet.owner.id and bet.betting_finished and not [true, false].include?(bet.outcome)
    %a.btn.btn-primary(data-toggle="modal" href="#complete-modal") Enter Outcome

.modal.fade#complete-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal" aria-hidden="true") &times;
        %h4.modal-title How'd it turn out?
      .modal-body
        / = link_to 'I was correct', complete_bet_path(bet, {correct: 'yes'}), method: :post, class: 'btn btn-success pull-right'
        %a.btn.btn-success.pull-right(data-method="post" href="#{bet_complete_path(bet, {choice: true})}") I was correct
        %a.btn.btn-danger(data-method="post" href="#{bet_complete_path(bet, {choice: false})}") I was incorrect

app/views/bets/_bet_partial.html.haml
/ %a{ data: { bind: 'foreach: userChoices' } }
/   %a{ data: { bind: 'text: user_id' } }
/   %a{ data: { bind: 'text: choice' } }  

/ %a{ data: { bind: 'text: challenge' } }
/ %a{ data: { bind: 'text: loser_task' } }

/ TODO:
/ Add 'complete' option which prompts if owner was correct or incorrect
/ Add file uploads for verification

- user_choice_for = bet.user_choice_for(current_user)
- bet_owner = bet.owner
- bet_disagreeing_choices = bet.disagreeing_choices
.row
  %table.bet
    %tr
      %td.agree-side
        = link_to bet.owner do
          = image_tag get_random_photo, class: (!bet.outcome ? 'loss ' : '') + 'img-thumbnail'
        - if not bet.user_choice_for(current_user) and bet.betting_allowed
          = link_to 'Agree', bet_agree_path(bet), method: :post, class: 'btn btn-success agreement-btn fullwidth'
      %td
        - if bet.outcome != nil
          - if bet.outcome
            %p.vs #{bet_owner.username.capitalize} wins
          - else
            %p.vs #{bet_disagreeing_choices.first.user.username.capitalize}
        - else
          %p.vs VS
        - choice = user_choice_for
        - if !(choice === nil)
          - if choice.choice != bet.outcome && !(bet.outcome === nil)
            %p You lost! 
            - if not choice.has_delivered
              = link_to 'Prove you followed through.', bet_verify_path(bet), method: :get
          - elsif choice.choice == bet.outcome && !(bet.outcome === nil)
            %p You won!
        %p.proposition-main
          %span.bolded= "#{bet_owner.username.capitalize} bets:"
          = link_to bet.proposition, bet
        %p.loser-task-main  
          %span= "The loser has to: #{bet.loser_task}"
        - if bet.event_start
          %p.cut-off
            %span= "Betting ends #{bet.event_start}"
      %td.disagree-side
        -if bet_disagreeing_choices.empty? and not user_choice_for and bet.betting_allowed
          = link_to 'Disagree', bet_disagree_path(bet), method: :post, class: 'btn btn-danger agreement-btn fullwidth'
        - elsif bet.disagreeing_choices.present?
          = link_to bet.disagreeing_choices.first.user do
            = image_tag get_random_photo, class: (bet.outcome ? 'loss ' : '') + 'img-thumbnail'

          - if not user_choice_for  and bet.betting_allowed
            = link_to 'Disagree', bet_disagree_path(bet), method: :post, class: 'btn btn-danger agreement-btn fullwidth'
  / %tr
  /   %td
  /     = link_to ''

app/views/bets/_bet_verifications.html.haml
- if not bet.betting_allowed
  %h3 Proof of loser tasks:

  - if bet.verified_choices.present?
    - bet.verified_choices.each do |choice|
      %h4= choice.user.username
      = image_tag choice.verification_file, class: 'img-thumbnail verification-photo'
  - else
    %p Nobody has proven they performed the task required. Get after those losers!

app/views/bets/_form.html.haml
= form_for @bet, class: 'form-horizontal' do |f|
  .form-group
    = f.label :proposition
    = f.text_area :proposition, class: 'form-control width300', rows: 4, placeholder: 'What you propose'
  .form-group
    = f.label :loser_task
    = f.text_area :loser_task, class: 'form-control width300', rows: 4, placeholder: 'Task that the user must do'
  .form-group
    = f.label :is_public, 'I want this bet to be public to anyone'
    = f.check_box :is_public
  .form-group
    = f.label :event_start, 'Betting cutoff time. When bets are no longer allowed'
    = f.datetime_select :event_start, class: 'form-control'
  = f.submit 'Bet', class: 'btn btn-primary'

app/views/bets/edit.html.haml
= form_for(@bet) do
  = render partial: 'form'

app/views/bets/index.html.haml
- if !@bets.empty?
  - @bets.each do |bet|
    = render 'bet_partial', bet: bet
    %div.divider

%div
  = link_to 'Challenge your friends!', new_bet_path

app/views/bets/new.html.haml
= form_for(@bet) do
  = render partial: 'form'

app/views/bets/show.html.haml
= render 'bet_partial', bet: @bet
= render 'bet_details', bet: @bet
= render 'bet_verifications', bet: @bet

app/views/bets/upload_verification.html.haml
%p #{@user_choice.verification_file.methods}
%p #{@user_choice.verification_file.class}

app/views/bets/verify.html.haml
Prove that you lived up to your end of the bet:

= @bet.loser_task
= form_for @bet, url: {action: "verify"}, class: 'form-horizontal' do |f|
  = f.file_field :verification_file
  = f.submit 'Upload', class: 'btn btn-primary'