config/routes.rb
Funbet::Application.routes.draw do
  root to: 'dashboards#index'

  resources :authentications
  resources :sessions
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

	get '/auth/:provider/callback', to: 'sessions#create'

  resources :users
  get 'register' => 'users#new', as: :register

  resources :bets do
    post 'agree' => 'bets#agree', as: :agree
    post 'disagree' => 'bets#disagree', as: :disagree
    post 'complete' => 'bets#complete', as: :complete
    get 'verify' => 'bets#verify', as: :verify
    put 'verify' => 'bets#upload_verification', as: :upload_verification
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	def authenticate_user!
		redirect_to login_path unless current_user
	end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	def set_current_user(user)
		@current_user = User.new(user)
		session[:user_id] = @current_user.id
	end

  def get_random_photo
    ['/assets/default_user.jpg','/assets/default_user2.jpg',
        '/assets/default_user3.jpg','/assets/default_user4.jpg',
        '/assets/default_user5.jpg','/assets/default_user6.jpg',
        '/assets/default_user7.jpg','/assets/default_user8.jpg'].sample
  end

  helper_method :current_user, :set_current_user, :get_random_photo
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.haml
- if flash
  - flash.each do |name, message|
    - if name.to_s == 'alert'
      .alert.alert-error= message
    - elsif name.to_s == 'notice'
      .alert.alert-success= message
    - else
      .alert.alert-warning= message

app/views/application/_topbar.html.haml
/ Menu Horizontal
.navbar.global-header.navbar-fixed-top.navbar-inverse
  .container{:data => { :dropdown => 'dropdown' }}
    - if current_user
      %button.navbar-toggle{ data: { toggle: 'collapse', target: '.main-nav-collapse'}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_url, class: 'navbar-brand branding brand' do
        %span Betly.io
      .navbar-collapse.collapse.main-nav-collapse
        %ul.nav.navbar-nav
          %li= link_to 'Bets', root_path
          %li= link_to 'New Bet', new_bet_path

        %ul.nav.navbar-nav.pull-right.topmenu
          %li= link_to 'My Account', edit_user_path(current_user)
          %li= link_to 'Log Out', logout_path
    - else
      %ul.nav.navbar-nav
        %li= link_to "Login", login_path
        %li= link_to "Register", register_path